# Generated by Django 5.0 on 2025-01-17 09:53

import Employee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employeeadditionalinformation_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadditionalinformation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeecertifications',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeeeducationachievements',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_achievements', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeelanguages',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeesoftskills',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeetechnicalskills',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_preferences', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
    ]
