# Generated by Django 5.0 on 2025-01-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employeeadditionalinformation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available_working_periods_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_working_periods_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_work_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
