# Generated by Django 5.0 on 2025-01-25 07:06

import Employee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_employeeworkpreferences_preferred_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkpreferences',
            name='preferred_job_category',
        ),
        migrations.CreateModel(
            name='PreferredJobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_category', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_job_categories', to='Employee.employee', verbose_name=Employee.models.Employee)),
            ],
        ),
    ]
