# Generated by Django 5.0 on 2025-01-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_remove_employee_address_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='academic_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
