# Generated by Django 5.0 on 2025-01-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_employeeeducation_academic_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecertifications',
            old_name='description',
            new_name='certification_description',
        ),
        migrations.RenameField(
            model_name='employeecertifications',
            old_name='image',
            new_name='certification_image',
        ),
        migrations.RenameField(
            model_name='employeecertifications',
            old_name='name',
            new_name='certification_name',
        ),
        migrations.RenameField(
            model_name='employeeeducationachievements',
            old_name='description',
            new_name='achievement_description',
        ),
        migrations.RenameField(
            model_name='employeeeducationachievements',
            old_name='name',
            new_name='achievement_name',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company_name',
            new_name='exp_company_name',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='description',
            new_name='exp_description',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='end_date',
            new_name='exp_end_date',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='job_title',
            new_name='exp_job_title',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='start_date',
            new_name='exp_start_date',
        ),
        migrations.RenameField(
            model_name='employeesoftskills',
            old_name='description',
            new_name='soft_description',
        ),
        migrations.RenameField(
            model_name='employeesoftskills',
            old_name='skill',
            new_name='soft_skill',
        ),
        migrations.RenameField(
            model_name='employeetechnicalskills',
            old_name='description',
            new_name='technical_description',
        ),
        migrations.RenameField(
            model_name='employeetechnicalskills',
            old_name='level',
            new_name='technical_level',
        ),
        migrations.RenameField(
            model_name='employeetechnicalskills',
            old_name='skill',
            new_name='technical_skill',
        ),
    ]
