# Generated by Django 5.0 on 2025-01-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_rename_description_employeecertifications_certification_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeelanguages',
            old_name='level',
            new_name='language_level',
        ),
    ]
