# Generated by Django 5.0 on 2025-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_rename_level_employeelanguages_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isoCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
