# Generated by Django 5.0 on 2025-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_employee_isocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isoCode',
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
