# Generated by Django 5.0 on 2025-01-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_remove_employee_isocode_alter_employee_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('cover_photo', models.ImageField(blank=True, upload_to='cover_photos/')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.JSONField(blank=True)),
                ('preferred_work_location', models.CharField(blank=True, max_length=100)),
                ('available_work_hours', models.PositiveIntegerField(blank=True)),
                ('available_working_periods_start_date', models.DateField(blank=True)),
                ('available_working_periods_end_date', models.DateField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
