# Generated by Django 5.0 on 2025-01-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_employeepersonalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePersonalInfo',
        ),
    ]
