# Generated by Django 5.0 on 2025-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0018_alter_employee_available_working_periods_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='available_working_periods_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_working_periods_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
