# Generated by Django 5.0 on 2025-01-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0022_alter_employee_available_working_periods_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='achievement_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
