# Generated by Django 5.0 on 2025-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0024_fieldofstudy_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='field_of_study',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='name_of_institution',
            field=models.CharField(max_length=500),
        ),
    ]
