# Generated by Django 5.0 on 2025-01-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0025_alter_employeeeducation_field_of_study_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
