# Generated by Django 5.0 on 2025-02-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_delete_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducation',
            name='current_academic_year',
        ),
    ]
