# Generated by Django 5.0 on 2025-02-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0027_remove_employeeeducation_current_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Employee.employee', verbose_name='Employee'),
        ),
    ]
