# Generated by Django 5.0 on 2025-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0030_alter_employeelanguages_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelanguages',
            name='language_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Fluent', 'Fluent'), ('Native', 'Native')], max_length=100),
        ),
    ]
