# Generated by Django 5.0 on 2025-02-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0032_alter_employeelanguages_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelanguages',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Employee.employee', verbose_name='Employee'),
        ),
    ]
