# Generated by Django 5.0 on 2025-02-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0033_alter_employeelanguages_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesoftskills',
            name='soft_description',
        ),
        migrations.RemoveField(
            model_name='employeetechnicalskills',
            name='technical_description',
        ),
    ]
