# Generated by Django 5.0 on 2025-02-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0034_remove_employeesoftskills_soft_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesoftskills',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeetechnicalskills',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='Employee.employee', verbose_name='Employee'),
        ),
    ]
