# Generated by Django 5.0 on 2025-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0035_alter_employeesoftskills_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='availability',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='transportation_availability',
            field=models.CharField(max_length=20),
        ),
    ]
