# Generated by Django 5.0 on 2025-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0036_alter_employeeworkpreferences_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='availability',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='interested_job_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeworkpreferences',
            name='transportation_availability',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
