# Generated by Django 5.0 on 2025-02-04 08:24

import Employee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0037_alter_employeeworkpreferences_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreferredjobcategory',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_job_categories', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
    ]
