# Generated by Django 5.0 on 2025-02-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0038_alter_employeepreferredjobcategory_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover_photos/')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Employee.employee', verbose_name='Employee')),
            ],
        ),
    ]
