# Generated by Django 5.0 on 2025-02-06 06:59

import Employee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0039_remove_employee_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='exp_description',
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='exp_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='employeeadditionalinformation',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='Employee.employee', verbose_name=Employee.models.Employee),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='exp_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
