# Generated by Django 5.0 on 2025-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0041_remove_employeeadditionalinformation_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadditionalinformation',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
