# Generated by Django 5.0 on 2025-02-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0042_employeeadditionalinformation_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadditionalinformation',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
