# Generated by Django 5.0 on 2025-02-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0043_alter_employeeadditionalinformation_willing_to_relocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='profile_pic',
        ),
    ]
