# Generated by Django 5.0 on 2025-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0044_remove_employeeprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
