# Generated by Django 5.0 on 2025-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0046_employee_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
