# Generated by Django 5.0 on 2025-02-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0047_employee_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='job_title',
        ),
    ]
