# Generated by Django 5.0 on 2025-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0048_remove_employeeprofile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
