# Generated by Django 5.0 on 2025-01-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_info', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('employer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfflineTalentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('vehicle_option', models.CharField(choices=[('with vehicle', 'with vehicle'), ('without vehicle', 'without vehicle')], default='without vehicle', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTalentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineJobInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('work_address', models.TextField()),
                ('age_requirement_min', models.PositiveIntegerField()),
                ('age_requirement_max', models.PositiveIntegerField()),
                ('preferred_academic_courses', models.TextField()),
                ('pay_structure', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_location_map', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.companyinfo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.offlinetalentcategories')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineJobInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('age_requirement_min', models.PositiveIntegerField()),
                ('age_requirement_max', models.PositiveIntegerField()),
                ('preferred_academic_courses', models.TextField()),
                ('pay_structure', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.companyinfo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.onlinetalentcategories')),
            ],
        ),
    ]
