# Generated by Django 5.0 on 2025-02-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_companyinfo_city_companyinfo_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinejobinformation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='onlinejobinformation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offlinejobinformation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='onlinejobinformation',
            name='category',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='OfflineJobInformation',
        ),
        migrations.DeleteModel(
            name='OnlineJobInformation',
        ),
    ]
