# Generated by Django 5.0 on 2025-02-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0006_companyinfo_offlinejobinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejobinformation',
            name='salary_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
