# Generated by Django 5.0 on 2025-02-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_onlinejobinformation_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='employer_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
