# Generated by Django 5.0 on 2025-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0009_remove_companyinfo_employer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinejobinformation',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
