# Generated by Django 5.0 on 2025-02-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_alter_onlinejobinformation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinejobinformation',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.onlinetalentcategories'),
        ),
    ]
