# Generated by Django 5.0 on 2025-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0012_alter_onlinejobinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinejobinformation',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
