# Generated by Django 5.0 on 2025-02-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0013_alter_onlinejobinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinejobinformation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.offlinetalentcategories'),
        ),
    ]
