# Generated by Django 5.0 on 2025-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0014_alter_offlinejobinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinejobinformation',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
