# Generated by Django 5.0 on 2025-02-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0015_alter_offlinejobinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinejobinformation',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_job_information', to='Employer.companyinfo', verbose_name='Company'),
        ),
    ]
