# Generated by Django 5.0 on 2025-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0016_alter_offlinejobinformation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinejobinformation',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='offlinejobinformation',
            name='work_address',
        ),
        migrations.AddField(
            model_name='offlinejobinformation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offlinejobinformation',
            name='country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinejobinformation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offlinejobinformation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offlinejobinformation',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
