# Generated by Django 5.0 on 2025-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0017_remove_offlinejobinformation_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinejobinformation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
