# Generated by Django 5.0 on 2025-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0018_alter_offlinejobinformation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinejobinformation',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinejobinformation',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
