# Generated by Django 5.0 on 2025-02-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0019_offlinejobinformation_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinejobinformation',
            name='job_type',
            field=models.CharField(default='offline', max_length=255),
        ),
        migrations.AddField(
            model_name='onlinejobinformation',
            name='job_type',
            field=models.CharField(default='online', max_length=255),
        ),
    ]
