# Generated by Django 5.0 on 2025-02-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0050_employeeslider'),
        ('Employer', '0021_employerslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinejobinformation',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='onlinejobinformation',
            name='posted_date',
        ),
        migrations.CreateModel(
            name='EmployerJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='job-application-resumes/')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='Employee.employee', verbose_name='Employee')),
                ('offline_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='Employer.offlinejobinformation', verbose_name='Offline Job')),
                ('online_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='Employer.onlinejobinformation', verbose_name='Online Job')),
            ],
        ),
    ]
